{{- define "file_header" -}}
// Code generated by cmd/template; DO NOT EDIT.
// service: {{ .Name }} {{ .Version }}

package {{ lower .Name }}
{{ end -}}

{{- define "method_line" }}// {{ .Comment }}（参数：{{ if .Params }}{{ join .Params ", " }}{{ else }}无{{ end }}）
g.{{ upper .HTTP }}("{{ .Path }}", {{ .Name }}Handler)
{{- end -}}
